name: Node.js CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.idea/*'
      - 'build/*'
      - 'public/*'
      - '.gitignore'
      - LICENSE
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - run: npm install
    - run: npm run build --if-present

    - name: Get Current DateTime
      id: getdate
      run: echo "::set-output name=dtVal::$(date +'%Y-%m-%d_%H.%M')"

    - name: Move build to seperate directory
      run: |
        mkdir ../build
        cp -R ./build/* ../build

    - name: Commit to ColdFerrin.github.io
      uses: actions/checkout@v4
      with:
        repository: 'ColdFerrin/ColdFerrin.github.io'
        ssh-key: '${{ secrets.ssh_key }}'

    - name: move build to deployment repo
      run: |
        cd ..
        cp -R build/* personal-repo
        cd personal-repo

    - name: Add Changes to repo
      run: |
        git config user.email "ferrinkatz@ferrinkatz.com"
        git config user.name "ColdFerrin"
        git add -A
        git commit -m "Auto build ${{steps.getdate.outputs.dtVal}}"
        git push || true

    env:
      CI: true
