name: Node.js CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.idea/*'
      - 'build/*'
      - 'public/*'
      - '.gitignore'
      - LICENSE
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build --if-present

    - name: Get Current DateTime
      id: getdate
      run: echo "::set-output name=dtVal::$(date +'%Y-%m-%d_%H.%M')"

    - name: test1
      run: |
        ls -la
        pwd
        cd ..

    - name: Commit to ColdFerrin.github.io
      uses: actions/checkout@v2
      with:
        repository: 'ColdFerrin/ColdFerrin.github.io'
        ssh-key: '${{ secrets.ssh_key }}'

    - name: test2
      run: |
        ls -la
        pwd
        cd ..
        ls -la
        pwd

    env:
      CI: true
