name: Node.js CI

on:
  push:
    paths-ignore:
      - build/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build --if-present

    - name: Get Current DateTime
      id: getdate
      run: echo "::set-output name=dtVal::$(date +'%Y-%m-%d_%H.%M')"

    - name: Add Changes to repo
      run: |
        git checkout -- build/CNAME
        git config user.email "ferrinkatz@ferrinkatz.com"
        git config user.name "ColdFerrin"
        git add -A
        git commit -m "Auto build ${{steps.getdate.outputs.dtVal}}"
        git push

    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: git@github.com:ColdFerrin/ColdFerrin.github.io.git
        BRANCH: master
        FOLDER: build
        SSH_PRIVATE_KEY: ${{ secrets.ssh_key }}

    env:
      CI: true
