name: Node.js CI

on:
  push:
    paths-ignore: 
      - build/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build --if-present
      
    - name: Get Current DateTim
      id: getdate
      run: echo "::set-output name=dtVal::$(date +'%Y-%m-%d_%H.%M')"
      
    - name: Deploy to Github Pages
      run: 
        git checkout -- build/CNAME
        git add -A
        git commit -m "Auto build ${{steps.getdate.outputs.dtVal}}"
        git push
        git subtree push --prefix=build https://github.com/ColdFerrin/ColdFerrin.github.io.git master

      env:
        CI: true
